#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

// include the composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// import the Symfony Console Application
use Symfony\Component\Console\Application;



$cli = new Application();
$cli->add(new DidbotCmd\Commands\AddCommand);
$cli->add(new DidbotCmd\Commands\ConfigApiTokenCommand);
$cli->add(new DidbotCmd\Commands\ConfigBaseUrlCommand);

// Default to the AddDid command
$did = new DidbotCmd\Commands\AddCommand;
$cli->setDefaultCommand($did->getName());

$cli->run();
?>